/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesAdvertisingRouteImport } from './routes/services.advertising'
import { Route as ServicesCreativeRouteImport } from './routes/services.creative'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdvertisingRoute = ServicesAdvertisingRouteImport.update({
  id: '/services/advertising',
  path: '/services/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreativeRoute = ServicesCreativeRouteImport.update({
  id: '/services/creative',
  path: '/services/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/creative': typeof ServicesCreativeRoute
  '/services/marketing': typeof ServicesMarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/creative': typeof ServicesCreativeRoute
  '/services/marketing': typeof ServicesMarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/advertising': typeof ServicesAdvertisingRoute
  '/services/creative': typeof ServicesCreativeRoute
  '/services/marketing': typeof ServicesMarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/services/advertising' | '/services/creative' | '/services/marketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/services/advertising' | '/services/creative' | '/services/marketing'
  id:
    | '__root__'
    | '/'
    | '/services/advertising'
    | '/services/creative'
    | '/services/marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesAdvertisingRoute: typeof ServicesAdvertisingRoute
  ServicesCreativeRoute: typeof ServicesCreativeRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/advertising': {
      id: '/services/advertising'
      path: '/services/advertising'
      fullPath: '/services/advertising'
      preLoaderRoute: typeof ServicesAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creative': {
      id: '/services/creative'
      path: '/services/creative'
      fullPath: '/services/creative'
      preLoaderRoute: typeof ServicesCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesAdvertisingRoute: ServicesAdvertisingRoute,
  ServicesCreativeRoute: ServicesCreativeRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
